services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=secure_app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ismaster')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/secure_app
      - JWT_SECRET=your_jwt_secret_change_this_in_production
      - NODE_ENV=development
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - GENERATE_SOURCEMAP=false
      - FAST_REFRESH=false
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_cache:/app/node_modules/.cache
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local
  frontend_cache:
    driver: local
